version: '3'

services:
  db:
    build: ./app/db # postgres db with postgis

    ports:
    - 5432:5432

    volumes:
      - ./app/db/data:/var/lib/postgresql/data

    environment:
      - POSTGRES_DB=sunspotter
      - POSTGRES_PASSWORD=GVHb52QJBu5Ih9BoQzKY

  sunspotter:
    build: ./app/sunspotter
    ports:
    - "3000:3000"
    
    volumes:
    - ./app/sunspotter/downloads:/opt/sunspotter/downloads

  tensorboard:
    image: tensorflow/tensorflow:latest-gpu

    ports:
    - "6006:6006"

    volumes:
    - ./code/jupyterNotebook/my_logs:/tf_logs

    command:
      tensorboard --logdir tf_logs/ --bind_all